/* Generated by Yosys 0.23 (git sha1 7ce5011c24b, gcc 11.3.0 -fPIC -Os) */

(* hdlname = "\\add5" *)
(* top =  1  *)
(* src = "test/add_cf.v:1.1-8.10" *)
module add5 (
    a,
    b,
    sum,
    cf
);
  (* unused_bits = "1 2 3 5 6 7" *)
  wire [8:0] _0_;
  (* src = "test/add_cf.v:2.17-2.18" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "test/add_cf.v:3.17-3.18" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "test/add_cf.v:5.12-5.14" *)
  output cf;
  wire cf;
  (* src = "test/add_cf.v:4.18-4.21" *)
  output [7:0] sum;
  wire [7:0] sum;
  (* module_not_derived = 32'd1 *) (* src = "test/add_cf.v:7.22-7.27|74_adder.v:52.26-58.10" *)
  \74AC283_1x1ADD4 _1_ (
      .A (a[3:0]),
      .B (b[3:0]),
      .CI(1'h0),
      .CO(_0_[4]),
      .S (sum[3:0])
  );
  (* module_not_derived = 32'd1 *) (* src = "test/add_cf.v:7.22-7.27|74_adder.v:52.26-58.10" *)
  \74AC283_1x1ADD4 _2_ (
      .A (a[7:4]),
      .B (b[7:4]),
      .CI(_0_[4]),
      .CO(cf),
      .S (sum[7:4])
  );
  assign {_0_[8], _0_[0]} = {cf, 1'h0};
endmodule
