/* Generated by Yosys 0.23 (git sha1 7ce5011c24b, gcc 11.3.0 -fPIC -Os) */

(* hdlname = "\\alu" *)
(* top =  1  *)
(* src = "test/alu.v:1.1-21.10" *)
module alu(a, b, clk, fi, su, s, cf, zf);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "test/alu.v:18.12-18.18" *)
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "test/alu.v:15.3-20.6|74_dffe.v:10.11-10.13" *)
  wire _13_;
  (* unused_bits = "1 2 3 5 6 7" *)
  wire [8:0] _14_;
  (* src = "test/alu.v:11.8-11.11" *)
  wire _cf;
  (* src = "test/alu.v:2.17-2.18" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "test/alu.v:3.17-3.18" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "test/alu.v:8.16-8.18" *)
  output cf;
  wire cf;
  (* src = "test/alu.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "test/alu.v:5.11-5.13" *)
  input fi;
  wire fi;
  (* src = "test/alu.v:7.18-7.19" *)
  output [7:0] s;
  wire [7:0] s;
  (* src = "test/alu.v:6.11-6.13" *)
  input su;
  wire su;
  (* src = "test/alu.v:9.16-9.18" *)
  output zf;
  wire zf;
  \74AC04_6x1NOT  _15_ (
    .A(fi),
    .Y(_13_)
  );
  \74AC32_4x1OR2  _16_ (
    .A(s[4]),
    .B(s[5]),
    .Y(_09_)
  );
  \74AC27_3x1NOR3  _17_ (
    .A(s[6]),
    .B(s[7]),
    .C(_09_),
    .Y(_10_)
  );
  \74AC32_4x1OR2  _18_ (
    .A(s[0]),
    .B(s[1]),
    .Y(_11_)
  );
  \74AC27_3x1NOR3  _19_ (
    .A(s[2]),
    .B(s[3]),
    .C(_11_),
    .Y(_12_)
  );
  \74AC08_4x1AND2  _20_ (
    .A(_10_),
    .B(_12_),
    .Y(_08_)
  );
  \74AC86_4x1XOR2  _21_ (
    .A(b[0]),
    .B(su),
    .Y(_00_)
  );
  \74AC86_4x1XOR2  _22_ (
    .A(su),
    .B(b[1]),
    .Y(_01_)
  );
  \74AC86_4x1XOR2  _23_ (
    .A(su),
    .B(b[2]),
    .Y(_02_)
  );
  \74AC86_4x1XOR2  _24_ (
    .A(su),
    .B(b[3]),
    .Y(_03_)
  );
  \74AC86_4x1XOR2  _25_ (
    .A(su),
    .B(b[4]),
    .Y(_04_)
  );
  \74AC86_4x1XOR2  _26_ (
    .A(su),
    .B(b[5]),
    .Y(_05_)
  );
  \74AC86_4x1XOR2  _27_ (
    .A(su),
    .B(b[6]),
    .Y(_06_)
  );
  \74AC86_4x1XOR2  _28_ (
    .A(su),
    .B(b[7]),
    .Y(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test/alu.v:13.21-13.38|74_adder.v:52.26-58.10" *)
  \74AC283_1x1ADD4  _29_ (
    .A(a[3:0]),
    .B({ _03_, _02_, _01_, _00_ }),
    .CI(1'h0),
    .CO(_14_[4]),
    .S(s[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test/alu.v:13.21-13.38|74_adder.v:52.26-58.10" *)
  \74AC283_1x1ADD4  _30_ (
    .A(a[7:4]),
    .B({ _07_, _06_, _05_, _04_ }),
    .CI(_14_[4]),
    .CO(_cf),
    .S(s[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test/alu.v:15.3-20.6|74_dffe.v:7.20-12.4" *)
  \74AC377_8x1DFFE  _31_ (
    .CE(_13_),
    .CP(clk),
    .D(_cf),
    .Q(cf)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "test/alu.v:15.3-20.6|74_dffe.v:7.20-12.4" *)
  \74AC377_8x1DFFE  _32_ (
    .CE(_13_),
    .CP(clk),
    .D(_08_),
    .Q(zf)
  );
  assign { _14_[8], _14_[0] } = { _cf, 1'h0 };
endmodule
